### ISSUE TITLE
Support for HEIC (iPhone format)

### ISSUE THREAD

**Issue by feliperaul** [cimon-io/ansible-role-imagemagick#5]
Hi there! Would it be possible to adapt this role to compile Imagemagick with HEIC support?

I found this tutorial (https://medium.com/@eplt/5-minutes-to-install-imagemagick-with-heic-support-on-ubuntu-18-04-digitalocean-fe2d09dcef1) but I'm having a hard time to port it to Ansible.

**Comment by merifri** [comment]
Hi.

Just add these libraries to `imagemagick_optional_dependencies` list:
 - libde265-dev
 - libheif-dev

And a configuration option for HEIC support: `--with-heic=yes`.

So, the role will look like this:

```yaml
    - role: ansible-role-imagemagick
      imagemagick_configure_options: "--with-modules --enable-shared --disable-static --without-magick-plus-plus --with-ltdl=yes --without-x --with-heic=yes"
      imagemagick_optional_dependencies:
        - libdjvulibre-dev
        - libopenexr-dev
        - liblcms2-2
        - libwmf-dev
        - libwebp-dev
        - libraw-dev
        - libfftw3-dev
        - liblqr-1-0-dev
        - libpango1.0-dev
        - libltdl-dev
        - libde265-dev
        - libheif-dev
```

```bash
$ identify -version
Version: ImageMagick 7.0.7-39 Q16 x86_64 2019-11-17 https://www.imagemagick.org
Copyright: © 1999-2018 ImageMagick Studio LLC
License: https://www.imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules OpenMP 
Delegates (built-in): bzlib djvu fftw fontconfig freetype heic jbig jng jpeg lcms lqr ltdl lzma openexr pangocairo png raw tiff webp wmf xml zlib
```
